### ISSUE TITLE
[Dépendance] Changer le nombre de jours crée une erreur TypeError

### ISSUE THREAD

**Issue by Zetrypio** [Zetrypio/TaskManager#20]
J'ai créé un lien entre la tâche du lundi à un autre :
J'ai ensuite changé l'affichage sur 1 Jour et j'ai obtenu :
```Python
bbox (2, 20, 806, 70)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\------\git\TaskManager\TaskManager\classGantt.py", line 132, in <lambda>
    self.mainCanvas.bind("<Configure>", lambda e:self.updateAffichage()) # Faire en sorte que la fenêtre se redessine si on redimensionne la fenêtre
  File "C:\Users\------\git\TaskManager\TaskManager\classGantt.py", line 165, in updateAffichage
    self.__afficherLesDependances()
  File "C:\Users\------\git\TaskManager\TaskManager\classGantt.py", line 209, in __afficherLesDependances
    lien.afficherLesLiens()
  File "C:\Users\------\git\TaskManager\TaskManager\classGantt.py", line 42, in afficherLesLiens
    x1F = self.canvas.bbox("num%s"%self.canvas.master.getIndiceTacheEnGantt(self.tacheF))[0]
TypeError: 'NoneType' object is not subscriptable
```
Cela viens du fait que
```py
self.canvas.master.getIndiceTacheEnGantt(self.tacheF)
```
renvoie `None`

**Comment by squelletton** [comment]
on verra ça quand je sortirais du "ugly mode" de l'affichage des liens

**Comment by squelletton** [comment]
Fait en attente de pouvoir changer de jour début (merge avec master)
