### ISSUE TITLE
Suppresstion de tache au lieu d'en faire une déplaçable

### ISSUE THREAD

**Issue by squelletton** [Zetrypio/TaskManager#85]
![image](https://user-images.githubusercontent.com/63096846/90252323-8c842d80-de3f-11ea-9506-48c09d935cdf.png)
### Comment reproduire
- Faire une tache fixe (avec début et fin)
- Faire un lien avec cette tache
- Transformer cette tache en "tache déplaçable"

La tache est toujours affichée sur les calendriers (tous, même après `updateAffichage()`), cependant elle n'existe plus.
A l'enreigistrement elle n'y est plus.

### Erreur dans la console 
```py
Traceback (most recent call last):
  File "...\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "...\TaskManager\TaskManager\schedulable\task\Task.py", line 172, in <lambda>
    rmenu.add_command(label="Transformer en une tâche déplaçable", command=lambda: self.transformToDnd(taskEditor, rmenu))
  File "...\TaskManager\TaskManager\schedulable\task\Task.py", line 546, in transformToDnd
    newTask.addSubTask(self)
  File "...\TaskManager\TaskManager\schedulable\task\Task.py", line 328, in addSubTask
    self.__subtasks.append(task)
AttributeError: 'Task' object has no attribute '_Task__subtasks'
```

**Comment by Zetrypio** [comment]
Issue déjà réglée en fait. Un commit l'avait corrigé, mais on ne l'a pas notifié apparement.
